"""empty message

Revision ID: 51215ddfc847
Revises: 
Create Date: 2021-06-25 11:38:07.941961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51215ddfc847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('usersVoted', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_table')
    # ### end Alembic commands ###
